version: '3'

services:
    db:
        image: mysql/mysql-server:8.0.29
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: .docker/php
        volumes:
            - ${APP_PATH}:/var/www/html
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    nginx:
        image: nginx:1.21.6-alpine
        volumes:
            - ${APP_PATH}:/var/www/html
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/nginx/sites/:/etc/nginx/sites-available/
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - php
        ports:
            - "888:80"
            - "8443:443"
